== code style

* ref. https://python-guideja.readthedocs.io/ja/latest/index.html[Python ヒッチハイク・ガイド]
* ref. https://python-guideja.readthedocs.io/ja/latest/writing/style.html#id5[Python ヒッチハイク・ガイド - コードスタイル - 関数の引数]

=== キーワード引数を使うかどうか

[quote, Python ヒッチハイク・ガイド - コードスタイル - 関数の引数]
____
キーワード引数 は必須ではなく、デフォルト値を持ちます。
これらは、関数に送信されるオプションのパラメータによく使用されます。
関数に2つまたは3つ以上の位置パラメータがある場合、そのシグネチャは覚えにくいため、キーワード引数をデフォルト値で使用すると便利です。
例えば、より完全な send 関数は send(message, to, cc=None, bcc=None) として定義できます。ここで、 cc と bcc はオプションで、別の値が渡されないときは None と評価されます。
____

「関数に2つまたは3つ以上の位置パラメータがある場合」とあるので、3つ以上の引数がある場合はキーワード引数がよいのかも。

=== アスタリスク (*)

* ref. https://qiita.com/LouiS0616/items/1bbe0a9bb93054f6c380[Python3.xのアスタリスク逆引き]

[source,python]
.アスタリスク * (仮引数名アリ)
----
def useless_func(a, b, *args, c, d):
    pass

useless_func(1, 2, 3, 4, 5, 6)     # NG
useless_func(1, 2, 3, 4, c=5, d=6) # OK

# OK の場合は次のように割り当てられる
# a: 1
# b: 2
# args: (3, 4)
# c: 5
# d: 6
----

[source,python]
.アスタリスク * (仮引数名ナシ)
----
# 仮引数名ナシの場合、以降(例では c, d)はキーワード引数を強制する
def useless_func(a, b, *, c, d):
    pass

useless_func(1, 2, 3, 4, c=5, d=6)  # NG
useless_func(1, 2, c=5, d=6)        # OK
# OK の場合は次のように割り当てられる
# a: 1
# b: 2
# c: 5
# d: 6
----

[source,python]
.アスタリスク **
----
# ** はキーワード引数を辞書にまとめる
def useless_func(**kwargs):
    print(kwargs)

useless_func(a=1, b=2, c=3)
# {'a': 1, 'b': 2, 'c': 3}
----

[source,python]
.ありとあらゆる引数を受け取る関数
----
def useless_func(*args, **kwargs):
    print(args, kwargs)

useless_func(1, 2, 3, a=1, b=2, c=3)
# (1, 2, 3) {'a': 1, 'b': 2, 'c': 3}
----

=== アンダーバー (_)

* ref. https://qiita.com/kiii142/items/6879cb065ad4c5f0b901[pythonのアンダーバーこれなんやねん]

[source,python]
.return値を無視するための_
----
H,W,_ = img.shape
----

[source,python]
._function(x): 関数前に1つ
----
def _single_leading_underscore(x):
    return n
#weak "internal use" indicator. E.g. from M import *
#does not import objects whose names start with an underscore.
----

[quote, _function(x): 関数前に1つ]
____
基本的に外部からの参照を受け付けない，ってものにはアンダーバーを1つつけるというのがpythonの習わしのようです。
____

[source,python]
.__function(x): クラス名の前に２つ
----
def __double_leading_underscore:
     return n
#when naming a class attribute, invokes name mangling
#(inside class FooBar, __boo becomes _FooBar__boo; see below).
----

[quote, __function(x): クラス名の前に２つ]
____
外部からのアクセスを受け付けませんよ対策の１つと言えるのではないかと思います。
____

[source,python]
.function(x)_： 関数後に1つ
----
def list_(x):
    return n
#used by convention to avoid conflicts with Python keyword
----

[quote, function(x)_： 関数後に1つ]
____
pythonの予約語をどーしても関数名に使いたい時には，後ろに１つ_つけてつかいわけろ，ということみたいです。
____

[source,python]
.__function__(x): 関数前後に2つずつ
----
def __double_leading_and_trailing_underscore__:
    return n
# "magic" objects or attributes that live in user-controlled
# namespaces. E.g. __init__, __import__ or __file__. Never invent
# such names; only use them as documented.``
----

[quote, __function__(x): 関数前後に2つずつ]
____
オブジェクトの振る舞いを変更したり，クラスの性質にあった動きをさせたい時に使うものなんだそうです。
____

ref. https://docs.python.org/ja/3/reference/datamodel.html#special-method-names[Python 言語リファレンス - 特殊メソッド名]
