== vmstat

* ref. https://access.redhat.com/ja/solutions/3054501[RedHat Customer Portal / Vmstat の出力結果はどのように解釈すれば良いですか?]

[source,bash]
----
# 1秒ごとに5回、情報を出力
DELAY=1
COUNT=5
vmstat ${DELAY} ${COUNT}
----

CPU ユーザーの負荷が高いケース::
+
--
[quote]
____
ユーザーが lame エンコーダーを使用して、標準のオーディオファイルを MP3 ファイルにエンコードしています。
____

cpu の us が 97% と高い数値を指している。

[source,bash]
----
[user@RHEL ~]$ vmstat 1 5
procs -----------memory---------- ---swap-- -----io---- --system-- -----cpu------
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 6  1      0 302380  16356 271852    0    0   561   568   80  590 43  7 43  7  0
 1  0      0 300892  16364 273256    0    0     0    52   79  274 97  3  0  0  0
 2  0      0 299544  16364 274532    0    0     0     0   78  372 97  3  0  0  0
 1  0      0 298292  16368 275780    0    0     0     0   53  255 97  3  0  0  0
 1  0      0 296820  16368 277192    0    0     0     0   77  377 97  3  0  0  0
[user@RHEL ~]$
----
--

CPU システムの負荷が高いケース::
+
--
[quote]
____
dd を実行して、ファイルに無作為なコンテンツを追加します。
このとき、カーネルによって生成された無作為な数値を /dev/urandom が提供します。
これにより、CPU における負荷が増えます (sy – system time)。
____

cpu の sy が 93%-98% と高い数値を指している。

[source,bash]
----
[user@RHEL ~]$ vmstat 1 5
procs -----------memory---------- ---swap-- -----io---- --system-- -----cpu------
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 2  0 402944  54000 161912 745324    5   14    54    59  221  867 13  3 82  2  0
 1  0 402944  53232 161916 748396    0    0     0     0   30  213  3 97  0  0  0
 1  0 402944  49752 161920 751452    0    0     0     0   28  290  4 96  0  0  0
 1  0 402944  45804 161924 755564    0    0     0     0   29  188  2 98  0  0  0
 1  0 402944  42568 161936 758608    0    0     0 17456  272  509  7 93  0  0  0
[user@RHEL ~]$
----
--

RAM ボトルネック(スワッピング)のケース::
+
--
[quote]
____
この例では、(VirtualBox における Windows ゲストシステムなど) 多くのアプリケーションが開きます。
ほとんどすべての作業メモリーが使用されています。
次に、1 つ以上のアプリケーション (OpenOffice) が起動します。
Linux カーネルが、OpenOffice のために RAM をさらに取得するために、ハードディスクのスワップファイルに複数のメモリーページをスワップアウトします。
____

swap の so(スワップアウト: ディスクにスワップされているメモリー) からスワップファイルにメモリーページをスワップしていることが示されている。

[source,bash]
----
[user@RHEL ~]$ vmstat 1 5
procs -----------memory---------- ---swap-- -----io---- --system-- -----cpu------
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 3  1 244208  10312   1552  62636    4   23    98   249   44  304 28  3 68  1  0
 0  2 244920   6852   1844  67284    0  544  5248   544  236 1655  4  6  0 90  0
 1  2 256556   7468   1892  69356    0 3404  6048  3448  290 2604  5 12  0 83  0
 0  2 263832   8416   1952  71028    0 3788  2792  3788  140 2926 12 14  0 74  0
 0  3 274492   7704   1964  73064    0 4444  2812  5840  295 4201  8 22  0 69  0
[user@RHEL ~]$
----
--

IO 読み込み負荷が高いケース::
+
--
[quote]
____
dd を使用して、/dev/null に大きなファイル (ISO ファイルなど) を読み書きします。
____

IO の読み込み負荷(bi 値)が高い。

[source,bash]
----
[user@RHEL ~]$ vmstat 1 5
procs -----------memory---------- ---swap-- -----io---- --system-- -----cpu------
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 3  1 465872  36132  82588 1018364    7   17    70   127  214  838 12  3 82  3  0
 0  1 465872  33796  82620 1021820    0    0 34592     0  357  781  6 10  0 84  0
 0  1 465872  36100  82656 1019660    0    0 34340     0  358  723  5  9  0 86  0
 0  1 465872  35744  82688 1020416    0    0 33312     0  345  892  8 11  0 81  0
 0  1 465872  35716  82572 1020948    0    0 34592     0  358  738  7  8  0 85  0
[user@RHEL ~]$
----
--

IO 書き込み負荷が高いケース::
+
--
[quote]
____
dd が /dev/zero から読み込み、ファイルに書き込みます。
oflag=dsync により、データが即座にディスクに書き込まれます (そしてページキャッシュには保存されません)。
____

IO の書き込み負荷(bo 値)が高い。

[source,bash]
----
[user@RHEL ~]$ vmstat 1 5
procs -----------memory---------- ---swap-- -----io---- --system-- -----cpu------
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 1  1      0  35628  14700 1239164    0    0  1740   652  117  601 11  4 66 20  0
 0  1      0  34852  14896 1239788    0    0     0 23096  300  573  3 16  0 81  0
 0  1      0  32780  15080 1241304    0    0     4 21000  344  526  1 13  0 86  0
 0  1      0  36512  15244 1237256    0    0     0 19952  276  394  1 12  0 87  0
 0  1      0  35688  15412 1237180    0    0     0 18904  285  465  1 13  0 86  0
[user@RHEL ~]$
----
--

CPU が IO を待っているケース::
+
--
[quote]
____
updatedb プロセスがすでに実行しています。
updatedb ユーティリティは mlocate の一部です。
これによりファイルシステム全体が調べられ locate コマンドに対してデータベースが作成されます (非常に早く実行されるファイル検索が使用されます)。
updatedb がファイルシステム全体からすべてのファイル名を読み込みますが、CPU は、IO システム (ハードディスク) からデータを取得するのを待つ必要があります。
____

CPU の wa(IO 待ち) の値が高い。

[source,bash]
----
procs -----------memory---------- ---swap-- -----io---- --system-- -----cpu------
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 2  1 403256 602848  17836 400356    5   15    50    50  207  861 13  3 83  1  0
 1  0 403256 601568  18892 400496    0    0  1048   364  337 1903  5  7  0 88  0
 0  1 403256 600816  19640 400568    0    0   748     0  259 1142  6  4  0 90  0
 0  1 403256 600300  20116 400800    0    0   476     0  196  630  8  5  0 87  0
 0  1 403256 599328  20792 400792    0    0   676     0  278 1401  7  5  0 88  0
[user@RHEL ~]$
----
--
